coverage_service: cobertura_xml
xcodeproj: Breeds.xcodeproj
workspace: Breeds.xcworkspace
input_format: profdata
output_directory: Coverage/
build_directory: build/Build/
scheme: CI
ignore:
  - BreedsTests/*
  - BreedsUITests/*

