disabled_rules:
  - line_length
  - force_try
  - identifier_name
  - trailing_whitespace
  - force_cast
  - colon
  - implicit_getter

opt_in_rules:
  - empty_count
  - comma

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
  - Fastlane
