# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Breeds.xcworkspace", scheme: "Breeds")
  end
  
  desc "Run unit test"
  lane :tests do
  run_tests(workspace: "Breeds.xcworkspace",
            devices: "iPhone 8",
            scheme: "CI",
            code_coverage: true)
  
      slather(
      sonarqube_xml: true,
      build_directory: "./DerivedData",
      input_format: "profdata",
      output_directory: "./reports",
      binary_basename: "CI",
      scheme: "CI",
      proj: "Breeds.xcodeproj",
      workspace: "Breeds.xcworspace"
    )
  end
end
