name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Cache CocoaPods libraries
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
      
    - name: Install Cocoapods
      run: pod install
      
    - name: Bundle update
      run: bundle update
      
    - name: Build and Tests
      run: fastlane tests
      
    - name: Post coverage
      uses: codecov/codecov-action@v2
      run: bash <(curl -s https://codecov.io/bash)
